"use client";

import { useState } from "react";
import { Check, Copy, Send } from "lucide-react";
export function InviteManager({ members }: { members: Array<{ id: string; name: string }> }) {
  const [email,setEmail]=useState(""); const [memberId,setMemberId]=useState(members[0]?.id ?? ""); const [link,setLink]=useState(""); const [error,setError]=useState(""); const [copied,setCopied]=useState(false); const [loading,setLoading]=useState(false);
  async function createInvite(event: React.FormEvent) { event.preventDefault(); setLoading(true);setError("");setLink(""); const response=await fetch("/api/invites",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,sourceMemberId:memberId})});const body=await response.json();setLoading(false);if(!response.ok){setError(body.error??"Could not create invite.");return;}setLink(body.url); }
  return <div><form onSubmit={createInvite}><div className="form-row"><label htmlFor="invite-email">Google account email</label><input className="input" id="invite-email" type="email" required value={email} onChange={(event)=>setEmail(event.target.value)} placeholder="friend@example.com"/></div><div className="form-row"><label htmlFor="invite-member">Connect to GroupMe member</label><select className="input" id="invite-member" value={memberId} onChange={(event)=>setMemberId(event.target.value)}>{members.map((member)=><option value={member.id} key={member.id}>{member.name}</option>)}</select></div><button className="button button-primary" disabled={loading}><Send size={16}/>{loading?"Creating…":"Create invite"}</button></form>{error&&<p style={{color:"#a92d39",fontSize:12}}>{error}</p>}{link&&<div className="privacy-note" style={{marginBottom:0}}><span style={{minWidth:0,flex:1,overflowWrap:"anywhere"}}>{link}</span><button className="button button-ghost" onClick={async()=>{await navigator.clipboard.writeText(link);setCopied(true);}}>{copied?<Check size={15}/>:<Copy size={15}/>}<span className="sr-only">Copy invite</span></button></div>}</div>;
}
